# DEPRICATED: TESTS FOR CV OUTPUT

Output analyzed by Diogo on 240119 and accepted

Implemented in 62897dc8fcfabb72c4fdd7cbdb98d27fd0ad9934

In [1]:
import subprocess

root_dir = subprocess.run(f'git rev-parse --show-toplevel', shell=True, stdout=subprocess.PIPE).stdout.decode().strip()
import sys
sys.path.append(root_dir + '/lib')

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
import re
from pathlib import Path

import plotly.express as px
import plotly.graph_objs as go
from plotly.subplots import make_subplots

import pandas as pd
pd.options.display.max_columns = None
pd.options.plotting.backend = 'plotly'

import moccalib as ml

from importlib import reload

from tqdm import tqdm

import subprocess

import logging
logger=logging.getLogger(__name__)

In [ ]:

import sqlalchemy as db
engine = db.create_engine('sqlite:///snapshot.db')
with engine.connect() as conn:
    print(conn.execute(db.text('select count(*) from snapshot')).fetchall())

In [ ]:
import sqlalchemy as db
engine = db.create_engine('sqlite:///snapshot.db')
with engine.connect() as conn:
    df = pd.read_sql('select * from snapshot where ik1==14 and ik2==14 limit 1000', con=conn)

In [ ]:
pwd

In [3]:
# reformats the write statement from the code to column names for reading with pandas
write_stm = """idbin, id1, id2, j1, j2, tphys, dtm,                                                                                                     & age, epoch(1),                                                                                                                                         
     & epoch(2), kstar(1), kstar(2), mass(1), mass(2), sep, ecc,                                                                                              
     &       rad(1), rad(2), lumin(1), lumin(2), massc(1), massc(2),                                                                                          
     &       radc(1), radc(2), menv(1), menv(2), renv(1), renv(2),                                                                                            
     &       ospin(1), ospin(2), dmt(1), dmt(2), dmr(1), dmr(2), rol(1),                                                                                      
     &       rol(2),dmdt(1), dmdt(2), dm1, dm2 , tb, Lx
"""
names = (re.sub("[^(\w]\d+[^)]", "", write_stm)  # remove line numbers
         .replace('&', '')  # remove continuation marks
         .replace(',', ' ')  # use only whitespaces as delimiters
         .replace('(','_')
         .replace(')','')
         .split()
        )
print(names)

['idbin', 'id1', 'id2', 'j1', 'j2', 'tphys', 'dtm', 'age', 'epoch_1', 'epoch_2', 'kstar_1', 'kstar_2', 'mass_1', 'mass_2', 'sep', 'ecc', 'rad_1', 'rad_2', 'lumin_1', 'lumin_2', 'massc_1', 'massc_2', 'radc_1', 'radc_2', 'menv_1', 'menv_2', 'renv_1', 'renv_2', 'ospin_1', 'ospin_2', 'dmt_1', 'dmt_2', 'dmr_1', 'dmr_2', 'rol_1', 'rol_2', 'dmdt_1', 'dmdt_2', 'dm1', 'dm2', 'tb', 'Lx']

In [4]:
datadir = Path("/work/chuck/mocca/gwiktoro/mocca/src/run")

In [5]:
# df = pd.read_csv(datadir / 'outputcv_short_test_ref5/cv.dat', names=names, sep='\s+')
df = pd.read_csv(datadir / 'outputcv_long_test_on2/cv.dat', names=names, sep='\s+')
df

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
0,782826,782827,782826,1,2,30.476517,-0.003880,1.165388,19.258057,29.311129,4,12,19.244862,1.377960,276.184304,0.0,166.745695,0.002787,1.618440e+05,0.749673,6.940812,1.377960,0.832771,0.002787,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,18.843639,2.487458e+07,1.187257e-21,1.935500e-09,6.066445e-07,4.980566e-15,166.779639,51.767995,-6.066445e-07,1.935495e-09,0.000000e+00,0.000000e+00,0.320385,0.0
1,782918,782919,782918,1,2,31.235001,0.010682,2.640662,19.573898,28.594339,4,12,18.585941,1.358854,208.023747,0.0,124.392516,0.003198,1.479672e+05,0.297004,6.557284,1.358854,0.811500,0.003198,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,28.841751,1.008388e+07,6.581280e-22,1.364668e-09,4.202306e-07,1.239520e-15,125.294539,39.234086,-4.202306e-07,1.364667e-09,0.000000e+00,0.000000e+00,0.212962,0.0
2,782616,782617,782616,1,2,32.297360,-0.004945,1.862102,20.476156,30.435258,4,12,18.408435,1.439876,250.112768,0.0,149.373315,0.000123,1.462937e+05,0.466846,6.557850,1.439876,0.807773,0.000123,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,22.778706,1.141694e+10,1.262028e-24,1.839250e-09,4.884867e-07,2.438738e-15,149.371304,48.123691,-4.884867e-07,1.839247e-09,0.000000e+00,0.000000e+00,0.281443,0.0
3,1071306,1071307,1071306,1,2,33.233815,-0.000399,4.971610,20.486459,28.262205,4,12,17.275931,1.331375,191.153603,0.0,114.373931,0.003720,1.255352e+05,0.140763,5.999259,1.331375,0.771335,0.003720,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,23.400649,4.647640e+06,3.077715e-22,1.143460e-09,3.173205e-07,4.032332e-16,114.375135,36.618518,-3.173205e-07,1.143460e-09,0.000000e+00,0.000000e+00,0.194214,0.0
4,782468,782469,782468,1,2,33.639693,-0.007383,1.798748,21.402572,31.840945,4,12,17.916099,1.411996,289.661748,0.0,172.776357,0.001861,1.389063e+05,0.475885,6.410924,1.411996,0.792526,0.001861,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,16.530232,5.798481e+07,1.998100e-22,1.993691e-09,5.176709e-07,2.505490e-15,172.824324,55.857676,-5.176709e-07,1.993688e-09,0.000000e+00,0.000000e+00,0.355460,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93777,345262,345263,345262,1,2,7605.354000,0.001000,7163.262435,-28829.583357,442.091565,0,11,0.363196,0.852637,1.437421,0.0,0.442236,0.009711,2.765298e-02,0.000017,0.000000,0.852637,0.000000,0.009711,3.355288e-01,1.000000e-10,3.963580e-01,1.000000e-10,12679.972540,1.465687e+07,5.137461e-26,0.000000e+00,0.000000e+00,5.471332e-22,0.442720,0.652984,-9.254508e-10,9.254508e-13,9.254508e-07,9.254508e-07,0.000495,0.0
93778,954356,954357,954356,1,2,7606.526000,0.001000,4701.112431,-5334.090784,2905.413569,0,11,0.565054,0.722921,1.482958,0.0,0.599928,0.011217,1.248866e-01,0.000024,0.000000,0.722921,0.000000,0.011217,1.112559e-01,1.000000e-10,2.177074e-01,1.000000e-10,12453.034460,7.010103e+06,3.489966e-25,0.000000e+00,0.000000e+00,9.001783e-22,0.530602,0.593807,-1.773055e-11,1.773055e-14,1.773055e-08,1.773055e-08,0.000504,0.0
93779,918430,918431,918430,1,2,7606.458000,0.001000,6954.416622,-7702.306155,652.041378,0,11,0.486945,0.709304,0.660587,0.0,0.541398,0.011382,6.364422e-02,0.000015,0.000000,0.709304,0.000000,0.011382,1.605180e-01,1.000000e-10,2.198354e-01,1.000000e-10,13396.824303,9.738564e+06,6.228456e-25,0.000000e+00,0.000000e+00,4.374612e-22,0.229133,0.272068,-4.522354e-09,4.522354e-12,4.522354e-06,4.522354e-06,0.000156,0.0
93780,83170,83171,83170,1,2,7606.265000,0.001000,7474.588149,-458059.321279,131.676851,0,11,0.016221,1.053975,0.651630,0.0,0.076141,0.007445,1.301508e-07,0.000020,0.000000,1.053975,0.000000,0.007445,1.622064e-02,1.000000e-10,7.614087e-02,1.000000e-10,38981.405922,2.694577e+07,2.417217e-28,0.000000e+00,0.000000e+00,6.974123e-22,0.076200,0.456253,-2.604635e-12,2.604634e-15,2.604635e-09,2.604635e-09,0.000161,0.0
93781,101500,101501,101500,1,2,7606.533000,0.001000,6923.054574,-19400.415357,683.478426,0,11,0.405692,0.700886,0.620002,0.0,0.477323,0.011485,3.597598e-02,0.000015,0.000000,0.700886,0.000000,0.011485,2.554730e-01,1.000000e-10,2.792594e-01,1.000000e-10,13673.729677,1.087161e+07,5.061955e-25,0.000000e+00,0.000000e+00,4.331481e-22,0.206280,0.264729,-2.915710e-09,2.915710e-12,2.915710e-06,2.915710e-06,0.000147,0.0

In [6]:
df.groupby('idbin').idbin.count().sort_values()

idbin
1071306      1
779184       1
779214       1
779228       1
320886       1
          ...
484644     105
752086     106
454704     114
777508     119
777592     123
Name: idbin, Length: 4354, dtype: int64

In [8]:
df.loc[lambda row: row.idbin==752086].sort_values('tphys')

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
10592,752086,752087,752086,1,2,632.289622,0.001,50.203311,1.563076,582.086311,1,11,1.257132,0.724423,2.468324,0.0,1.044478,0.011199,4.609573,0.005109,0.0,0.724423,0.0,0.011199,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,6108.977927,1.383621e+05,1.921545e-21,0.0,0.0,2.777669e-18,1.054907,0.820329,-6.194607e-10,6.194607e-10,6.194607e-07,6.194607e-07,0.000873,0.0
11108,752086,752087,752086,1,2,654.930000,0.001,22.417984,-14.312427,632.512016,1,11,1.247132,0.734423,1.999195,0.0,1.044359,0.011079,4.479544,0.013373,0.0,0.734423,0.0,0.011079,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,9603.672475,4.418711e+05,1.145650e-20,0.0,0.0,1.176195e-17,0.850559,0.667984,-4.033424e-10,4.033424e-10,4.033424e-07,4.033424e-07,0.000637,0.0
11429,752086,752087,752086,1,2,668.801000,0.001,36.288984,-31.452689,632.512016,1,11,1.237131,0.744423,1.792150,0.0,1.043011,0.010960,4.344478,0.007694,0.0,0.744423,0.0,0.010960,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,11132.133105,1.398207e+06,5.787314e-21,0.0,0.0,5.132587e-18,0.759038,0.601992,-1.473146e-09,1.473146e-09,1.473146e-06,1.473146e-06,0.000540,0.0
11569,752086,752087,752086,1,2,673.994000,0.001,41.481984,-49.453308,632.512016,1,11,1.227130,0.754424,1.622548,0.0,1.040907,0.010842,4.202993,0.006661,0.0,0.754424,0.0,0.010842,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,12644.853049,2.372062e+06,5.293963e-21,0.0,0.0,4.135048e-18,0.684116,0.547899,-3.338240e-09,3.338240e-09,3.338240e-06,3.338240e-06,0.000465,0.0
11652,752086,752087,752086,1,2,676.646000,0.001,44.133984,-68.236459,632.512016,1,11,1.217128,0.764426,1.500641,0.0,1.038388,0.010724,4.062136,0.006275,0.0,0.764426,0.0,0.010724,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,13897.751761,3.364354e+06,5.275481e-21,0.0,0.0,3.780346e-18,0.629874,0.509389,-5.548222e-09,5.548222e-09,5.548222e-06,5.548222e-06,0.000414,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17673,752086,752087,752086,1,2,842.735000,0.001,210.222984,-93406.362461,632.512016,0,11,0.246401,0.800448,0.472000,0.0,0.338368,0.010306,0.013736,0.001044,0.0,0.800448,0.0,0.010306,2.464004e-01,1.000000e-10,3.383682e-01,1.000000e-10,13605.103015,1.692496e+07,1.182036e-22,0.0,0.0,2.564469e-19,0.133558,0.228027,-1.463152e-09,1.463151e-12,1.463152e-06,1.463152e-06,0.000100,0.0
17938,752086,752087,752086,1,2,849.603000,0.001,217.090984,-101659.333230,632.512016,0,11,0.236399,0.800458,0.452954,0.0,0.328831,0.010306,0.012748,0.001005,0.0,0.800458,0.0,0.010306,2.363991e-01,1.000000e-10,3.288307e-01,1.000000e-10,14444.333319,1.692755e+07,1.110616e-22,0.0,0.0,2.422730e-19,0.126763,0.220482,-1.452100e-09,1.452100e-12,1.452100e-06,1.452100e-06,0.000095,0.0
18211,752086,752087,752086,1,2,856.473000,0.001,223.960984,-111009.743867,632.512016,0,11,0.226398,0.800468,0.431451,0.0,0.319168,0.010306,0.011773,0.000969,0.0,0.800468,0.0,0.010306,2.263983e-01,1.000000e-10,3.191680e-01,1.000000e-10,15582.955957,1.693001e+07,1.055822e-22,0.0,0.0,2.292845e-19,0.119359,0.211659,-1.463200e-09,1.463199e-12,1.463200e-06,1.463200e-06,0.000089,0.0
18480,752086,752087,752086,1,2,863.229000,0.001,230.716984,-121667.035625,632.512016,0,11,0.216398,0.800478,0.406940,0.0,0.309373,0.010306,0.010810,0.000935,0.0,0.800478,0.0,0.010306,2.163983e-01,1.000000e-10,3.093726e-01,1.000000e-10,20563.102952,1.693235e+07,1.020387e-22,0.0,0.0,2.175440e-19,0.111221,0.201251,-1.504141e-09,1.504141e-12,1.504141e-06,1.504141e-06,0.000082,0.0
18713,752086,752087,752086,1,2,869.714000,0.001,237.201984,-133893.548258,632.512016,0,11,0.206398,0.800488,0.378455,0.0,0.299436,0.010306,0.009859,0.000905,0.0,0.800488,0.0,0.010306,2.063982e-01,1.000000e-10,2.994358e-01,1.000000e-10,12817.284309,1.693458e+07,1.010651e-22,0.0,0.0,2.071360e-19,0.102125,0.188734,-1.590775e-09,1.590775e-12,1.590775e-06,1.590775e-06,0.000074,0.0

In [22]:
# df = pd.read_csv(datadir / 'outputcv_short_test_ref4/cv.dat', names=names, sep='\s+')
df

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
0,78268,78269,78268,1,2,33.522387,-0.000112,1.794507,21.343203,31.727880,4,12,17.974375,1.400973,266.490956,0.0,159.237668,0.002201,139336.829376,0.473417,6.405411,1.400973,0.794678,0.002201,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,19.625727,3.772770e+07,3.377902e-22,1.721039e-09,4.715752e-07,2.502936e-15,159.223961,51.221600,-4.715752e-07,1.721037e-09,0.000000,0.000000,0.313291,0.0
1,78234,78235,78234,1,2,34.831436,-0.004424,1.688201,22.305210,33.143235,4,12,17.562219,1.346474,250.234163,0.0,149.808191,0.003442,132045.389127,0.487087,6.216798,1.346474,0.782192,0.003442,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,21.827613,1.399742e+07,1.005333e-21,1.542282e-09,4.264124e-07,2.603424e-15,149.823155,47.863323,-4.264124e-07,1.542279e-09,0.000000,0.000000,0.288561,0.0
2,107116,107117,107116,1,2,36.490429,-0.005365,4.230232,22.949755,32.260197,4,12,16.513056,1.383664,253.401391,0.0,149.854188,0.002653,115217.067124,0.176282,5.796403,1.383664,0.749770,0.002653,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,14.109628,1.629952e+07,1.056480e-22,1.518530e-09,3.574014e-07,5.645065e-16,150.003169,49.755410,-3.574014e-07,1.518530e-09,0.000000,0.000000,0.302256,0.0
3,78226,78227,78226,1,2,36.138209,-0.006051,2.740063,22.952661,33.398146,4,12,16.887585,1.385517,316.046242,0.0,187.454728,0.002608,122471.536878,0.290365,6.021880,1.385517,0.759663,0.002608,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,11.423477,2.664463e+07,1.449651e-22,1.902818e-09,4.644067e-07,1.194382e-15,187.597515,61.671864,-4.644067e-07,1.902817e-09,0.000000,0.000000,0.416647,0.0
4,78270,78271,78270,1,2,36.921581,-0.007778,4.946327,22.956721,31.975254,4,12,16.156016,1.426613,347.044083,0.0,203.768615,0.001283,111438.472339,0.151724,5.754076,1.426613,0.734833,0.001283,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,6.634817,8.504622e+07,9.478756e-24,2.072392e-09,4.410936e-07,4.502429e-16,204.031509,69.199149,-4.410936e-07,2.072392e-09,0.000000,0.000000,0.488746,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8131,77688,77689,77688,1,2,145.666054,0.000646,69.104246,30.269263,76.561808,2,12,4.483116,1.178279,43.623055,0.0,25.577632,0.005956,1267.209904,0.005704,0.740725,1.178279,0.161008,0.005956,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,134.656465,4.352748e+05,1.057067e-23,3.816448e-11,1.226230e-09,3.275449e-18,21.681478,11.832512,-2.172745e-07,2.160864e-07,0.000140,0.000140,0.038385,0.0
8132,77688,77689,77688,1,2,145.666700,0.000646,69.104892,30.261166,76.561808,2,12,4.482969,1.178425,43.613019,0.0,25.641447,0.005954,1266.943355,0.005704,0.740725,1.178425,0.161008,0.005954,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,134.965672,4.633903e+05,1.056770e-23,3.815748e-11,1.225709e-09,3.275977e-18,21.675888,11.830292,-2.283966e-07,2.272091e-07,0.000148,0.000147,0.038372,0.0
8133,77688,77689,77688,1,2,145.667346,0.000646,69.105538,30.252658,76.561808,2,12,4.482814,1.178580,43.602765,0.0,25.705355,0.005952,1266.669504,0.005705,0.740725,1.178580,0.161008,0.005952,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,135.259092,4.929553e+05,1.056444e-23,3.815057e-11,1.225176e-09,3.276535e-18,21.670159,11.828038,-2.399081e-07,2.387211e-07,0.000155,0.000154,0.038358,0.0
8134,77688,77689,77688,1,2,145.667992,0.000646,69.106185,30.243726,76.561808,2,12,4.482651,1.178742,43.592283,0.0,25.769354,0.005950,1266.388100,0.005706,0.740725,1.178742,0.161008,0.005950,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,135.536570,5.240234e+05,1.056088e-23,3.814374e-11,1.224630e-09,3.277124e-18,21.664286,11.825749,-2.518176e-07,2.506311e-07,0.000163,0.000162,0.038344,0.0
8135,77688,77689,77688,1,2,145.668639,0.000646,69.106831,30.234355,76.561808,2,12,4.482480,1.178912,43.581559,0.0,25.833439,0.005948,1266.098885,0.005706,0.740725,1.178912,0.161008,0.005948,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,135.797944,5.566499e+05,1.055702e-23,3.813700e-11,1.224070e-09,3.277745e-18,21.658260,11.823421,-2.641337e-07,2.629477e-07,0.000171,0.000170,0.038330,0.0

In [6]:
df.sort_values(['idbin','tphys'])

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
122846,28006,28007,28006,1,2,701.400191,0.001000,82.873193,1.904826,618.526998,1,11,1.233997,0.711225,2.459080,0.0,1.041947,0.011359,4.291637,0.002779,0.000000,0.711225,0.000000,0.011359,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,6942.054849,1.083953e+05,7.976014e-22,0.000000e+00,0.000000e+00,1.114284e-18,1.050915,0.817295,-8.569600e-09,8.569600e-09,8.569600e-06,8.569600e-06,0.000876,0.0
65030,31426,31427,31426,1,2,501.563118,0.001000,276.387342,1.432627,225.175776,1,11,1.163189,0.915643,2.536400,0.0,1.006034,0.009003,3.119638,0.000865,0.000000,0.915643,0.000000,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,6982.221516,2.606279e+00,4.498158e-23,0.000000e+00,0.000000e+00,1.933440e-19,1.014048,0.909047,-1.010447e-15,8.171029e-19,1.010447e-12,1.010447e-12,0.000888,0.0
65298,31426,31427,31426,1,2,502.001000,0.001000,276.825224,1.432008,225.175776,1,11,1.163189,0.915643,2.525161,0.0,1.006048,0.009003,3.119888,0.000863,0.000000,0.915643,0.000000,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7052.458550,5.451584e+01,4.524670e-23,0.000000e+00,0.000000e+00,1.928032e-19,1.009555,0.905019,-8.943072e-12,8.942879e-15,8.943072e-09,8.943072e-09,0.000882,0.0
65566,31426,31427,31426,1,2,503.001000,0.001000,277.825224,-4.868681,225.175776,1,11,1.158661,0.915648,2.514350,0.0,1.004138,0.009003,3.068203,0.000859,0.000000,0.915648,0.000000,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7067.948990,5.167876e+05,4.499023e-23,0.000000e+00,0.000000e+00,1.915784e-19,1.004370,0.901978,-6.848624e-09,6.848624e-12,6.848624e-06,6.848624e-06,0.000878,0.0
65833,31426,31427,31426,1,2,504.001000,0.001000,278.825224,-14.495092,225.175776,1,11,1.151911,0.915654,2.510182,0.0,1.001155,0.009003,2.991984,0.000856,0.000000,0.915654,0.000000,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7075.010459,1.264924e+06,4.433507e-23,0.000000e+00,0.000000e+00,1.903665e-19,1.001415,0.901730,-6.652899e-09,6.652899e-12,6.652899e-06,6.652899e-06,0.000877,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,1071164,1071165,1071164,1,2,35.889589,-0.005965,5.302407,22.366611,30.587182,4,12,16.489319,1.366820,192.087686,0.0,113.704855,0.003033,113135.074740,0.134128,5.686014,1.366820,0.747411,0.003033,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,21.850527,7.293444e+06,1.626787e-22,1.176385e-09,2.808035e-07,3.743770e-16,113.867378,37.596717,-2.808035e-07,1.176385e-09,0.000000e+00,0.000000e+00,0.199712,0.0
38,1071168,1071169,1071168,1,2,37.004692,-0.000461,0.956004,22.578206,36.048688,4,11,16.161711,0.981677,177.410379,0.0,109.293281,0.008264,100826.426065,0.661154,5.356780,0.981677,0.722021,0.008264,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,42.663792,1.363292e+06,2.898243e-20,5.702731e-10,2.367629e-07,4.120877e-15,109.277746,31.663068,-2.367629e-07,5.702690e-10,0.000000e+00,0.000000e+00,0.180912,0.0
27,1071262,1071263,1071262,1,2,36.861378,-0.009519,6.987033,22.386730,29.874345,4,12,15.608208,1.197678,149.549519,0.0,89.242403,0.005707,98430.664146,0.085320,5.244278,1.197678,0.715006,0.005707,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,29.072377,9.895603e+05,5.607031e-22,7.174094e-10,1.946958e-07,1.897192e-16,89.530458,28.612129,-1.946958e-07,7.174092e-10,0.000000e+00,0.000000e+00,0.141415,0.0
51,1071274,1071275,1071274,1,2,38.749820,-0.006563,10.363523,22.749634,28.386296,4,12,14.614874,1.372510,539.997895,0.0,314.589264,0.002910,90655.444380,0.061738,5.257719,1.372510,0.667746,0.002910,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,1.516852,1.262104e+07,4.616381e-24,2.439017e-09,4.715856e-07,1.168219e-16,314.879798,109.631285,-4.715856e-07,2.439017e-09,0.000000e+00,0.000000e+00,0.994827,0.0
3,1071306,1071307,1071306,1,2,33.233815,-0.000399,4.971610,20.486459,28.262205,4,12,17.275931,1.331375,191.153603,0.0,114.373931,0.003720,125535.181404,0.140763,5.999259,1.331375,0.771335,0.003720,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,23.400649,4.647640e+06,3.077715e-22,1.143460e-09,3.173205e-07,4.032332e-16,114.375135,36.618518,-3.173205e-07,1.143460e-09,0.000000e+00,0.000000e+00,0.194214,0.0

In [14]:
i = 5
for ids,dfg in df.groupby(['idbin','id1','id2']):
    print(f"{ids=}")
    df0 = dfg.sort_values('tphys')
    df1 = df0['mass_1'].where(df0['j1']==1, df0['mass_2'])
    display(df0[df1.diff().abs()<0.01])
    if (i:=i-1)<0:
        break

ids=(28006, 28007, 28006)

Empty DataFrame
Columns: [idbin, id1, id2, j1, j2, tphys, dtm, age, epoch_1, epoch_2, kstar_1, kstar_2, mass_1, mass_2, sep, ecc, rad_1, rad_2, lumin_1, lumin_2, massc_1, massc_2, radc_1, radc_2, menv_1, menv_2, renv_1, renv_2, ospin_1, ospin_2, dmt_1, dmt_2, dmr_1, dmr_2, rol_1, rol_2, dmdt_1, dmdt_2, dm1, dm2, tb, Lx]
Index: []

ids=(31426, 31427, 31426)

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
65298,31426,31427,31426,1,2,502.001,0.001,276.825224,1.432008,225.175776,1,11,1.163189,0.915643,2.525161,0.0,1.006048,0.009003,3.119888,0.000863,0.0,0.915643,0.0,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7052.458550,5.451584e+01,4.524670e-23,0.0,0.0,1.928032e-19,1.009555,0.905019,-8.943072e-12,8.942879e-15,8.943072e-09,8.943072e-09,0.000882,0.0
65566,31426,31427,31426,1,2,503.001,0.001,277.825224,-4.868681,225.175776,1,11,1.158661,0.915648,2.514350,0.0,1.004138,0.009003,3.068203,0.000859,0.0,0.915648,0.0,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7067.948990,5.167876e+05,4.499023e-23,0.0,0.0,1.915784e-19,1.004370,0.901978,-6.848624e-09,6.848624e-12,6.848624e-06,6.848624e-06,0.000878,0.0
65833,31426,31427,31426,1,2,504.001,0.001,278.825224,-14.495092,225.175776,1,11,1.151911,0.915654,2.510182,0.0,1.001155,0.009003,2.991984,0.000856,0.0,0.915654,0.0,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7075.010459,1.264924e+06,4.433507e-23,0.0,0.0,1.903665e-19,1.001415,0.901730,-6.652899e-09,6.652899e-12,6.652899e-06,6.652899e-06,0.000877,0.0
66102,31426,31427,31426,1,2,505.001,0.001,279.825224,-24.127186,225.175776,1,11,1.145350,0.915661,2.505789,0.0,0.998118,0.009003,2.919199,0.000852,0.0,0.915661,0.0,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7083.284238,1.967310e+06,4.370963e-23,0.0,0.0,1.891664e-19,0.998405,0.901370,-6.470122e-09,6.470121e-12,6.470122e-06,6.470122e-06,0.000876,0.0
66373,31426,31427,31426,1,2,506.001,0.001,280.825224,-33.772632,225.175776,1,11,1.138966,0.915667,2.501194,0.0,0.995033,0.009003,2.849573,0.000849,0.0,0.915667,0.0,0.009003,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,7092.662970,2.628270e+06,4.311146e-23,0.0,0.0,1.879782e-19,0.995345,0.900907,-6.300942e-09,6.300942e-12,6.300942e-06,6.300942e-06,0.000875,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472590,31426,31427,31426,1,2,1414.001,0.001,772.769044,-4400.245753,641.231956,0,11,0.636060,0.916445,1.679696,0.0,0.650985,0.008994,0.198124,0.000257,0.0,0.916445,0.0,0.008994,8.546864e-02,1.000000e-10,2.239356e-01,1.000000e-10,14085.339402,1.116009e+06,4.930789e-24,0.0,0.0,3.138462e-20,0.584162,0.690175,-1.541561e-11,1.541558e-14,1.541561e-08,1.541561e-08,0.000554,0.0
473219,31426,31427,31426,1,2,1415.001,0.001,773.769044,-4400.704523,641.231956,0,11,0.636047,0.916445,1.679676,0.0,0.650975,0.008994,0.198110,0.000257,0.0,0.916445,0.0,0.008994,8.547241e-02,1.000000e-10,2.239343e-01,1.000000e-10,14085.574994,1.117480e+06,4.919421e-24,0.0,0.0,3.131287e-20,0.584153,0.690170,-1.541580e-11,1.541576e-14,1.541580e-08,1.541580e-08,0.000554,0.0
473847,31426,31427,31426,1,2,1416.001,0.001,774.769044,-4401.163421,641.231956,0,11,0.636034,0.916445,1.679657,0.0,0.650966,0.008994,0.198096,0.000256,0.0,0.916445,0.0,0.008994,8.547618e-02,1.000000e-10,2.239330e-01,1.000000e-10,14085.810611,1.118952e+06,4.908094e-24,0.0,0.0,3.124138e-20,0.584143,0.690166,-1.541598e-11,1.541595e-14,1.541598e-08,1.541598e-08,0.000554,0.0
474480,31426,31427,31426,1,2,1417.001,0.001,775.769044,-4401.622445,641.231956,0,11,0.636020,0.916445,1.679638,0.0,0.650956,0.008994,0.198082,0.000256,0.0,0.916445,0.0,0.008994,8.547995e-02,1.000000e-10,2.239317e-01,1.000000e-10,14086.046252,1.120423e+06,4.896807e-24,0.0,0.0,3.117015e-20,0.584133,0.690161,-1.541617e-11,1.541614e-14,1.541617e-08,1.541617e-08,0.000554,0.0
475113,31426,31427,31426,1,2,1418.001,0.001,776.769044,-4402.081597,641.231956,0,11,0.636007,0.916445,1.679619,0.0,0.650947,0.008994,0.198067,0.000256,0.0,0.916445,0.0,0.008994,8.548372e-02,1.000000e-10,2.239304e-01,1.000000e-10,14086.281915,1.121894e+06,4.885561e-24,0.0,0.0,3.109916e-20,0.584124,0.690156,-1.541636e-11,1.541633e-14,1.541636e-08,1.541636e-08,0.000554,0.0

ids=(31542, 31543, 31542)

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
324507,31542,31543,31542,1,2,1136.001,0.001,0.255592,-18.624825,1135.745408,1,11,0.779782,0.624103,1.816150,0.0,0.726896,0.012457,0.478686,1.518421,0.0,0.624103,0.0,0.012457,0.058038,1.000000e-10,0.228045,1.000000e-10,9685.753542,4.379496e+05,1.152134e-17,0.0,0.0,1.430102e-14,0.723447,0.653469,-1.943197e-15,-1.234631e-14,1.943197e-12,1.954718e-12,0.000655,0.0
324996,31542,31543,31542,1,2,1137.001,0.001,1.255592,-18.625035,1135.745408,1,11,0.779782,0.624103,1.796435,0.0,0.729028,0.012457,0.478709,0.313043,0.0,0.624103,0.0,0.012457,0.058038,1.000000e-10,0.228714,1.000000e-10,10121.875056,4.379528e+05,1.097194e-18,0.0,0.0,1.333789e-15,0.715593,0.646375,-1.171728e-13,1.158401e-13,1.171728e-10,1.171739e-10,0.000644,0.0
325486,31542,31543,31542,1,2,1138.001,0.001,2.255592,-18.626449,1135.745408,1,11,0.779781,0.624103,1.779608,0.0,0.730957,0.012457,0.478731,0.163094,0.0,0.624103,0.0,0.012457,0.058038,1.000000e-10,0.229320,1.000000e-10,10516.140942,4.379742e+05,4.198607e-19,0.0,0.0,5.013000e-16,0.708890,0.640321,-5.248008e-13,5.242999e-13,5.248008e-10,5.248012e-10,0.000635,0.0
325975,31542,31543,31542,1,2,1139.001,0.001,3.255592,-18.630536,1135.745408,1,11,0.779781,0.624104,1.765213,0.0,0.732701,0.012457,0.478752,0.107426,0.0,0.624104,0.0,0.012457,0.058039,1.000000e-10,0.229867,1.000000e-10,10870.959211,4.380360e+05,2.279036e-19,0.0,0.0,2.679211e-16,0.703156,0.635142,-1.270739e-12,1.270471e-12,1.270739e-09,1.270739e-09,0.000627,0.0
326463,31542,31543,31542,1,2,1140.001,0.001,4.255592,-18.638785,1135.745408,1,11,0.779779,0.624106,1.752849,0.0,0.734278,0.012457,0.478770,0.078966,0.0,0.624106,0.0,0.012457,0.058039,1.000000e-10,0.230362,1.000000e-10,11189.641707,4.381605e+05,1.455537e-19,0.0,0.0,1.688316e-16,0.698230,0.630694,-2.325010e-12,2.324842e-12,2.325010e-09,2.325011e-09,0.000621,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402950,31542,31543,31542,1,2,1294.001,0.001,158.255592,-7843.635938,1135.745408,0,11,0.440490,0.647338,0.636192,0.0,0.505211,0.012155,0.041482,0.001180,0.0,0.647338,0.0,0.012155,0.207346,1.000000e-10,0.239426,1.000000e-10,55469.651412,1.098449e+07,5.215611e-22,0.0,0.0,3.082154e-19,0.220201,0.262519,-3.333704e-09,3.333703e-12,3.333704e-06,3.333704e-06,0.000154,0.0
403479,31542,31543,31542,1,2,1295.001,0.001,159.255592,-8028.504678,1135.745408,0,11,0.437175,0.647342,0.634565,0.0,0.502584,0.012155,0.040523,0.001171,0.0,0.647342,0.0,0.012155,0.211384,1.000000e-10,0.241969,1.000000e-10,55565.095247,1.100683e+07,5.106933e-22,0.0,0.0,3.048026e-19,0.219236,0.262272,-3.273935e-09,3.273934e-12,3.273935e-06,3.273935e-06,0.000154,0.0
404008,31542,31543,31542,1,2,1296.001,0.001,160.255592,-8213.693477,1135.745408,0,11,0.433919,0.647345,0.632987,0.0,0.499998,0.012155,0.039608,0.001163,0.0,0.647345,0.0,0.012155,0.215453,1.000000e-10,0.244676,1.000000e-10,55626.703117,1.102825e+07,5.000985e-22,0.0,0.0,3.014486e-19,0.218296,0.262038,-3.215359e-09,3.215359e-12,3.215359e-06,3.215359e-06,0.000154,0.0
404538,31542,31543,31542,1,2,1297.001,0.001,161.255592,-8399.185130,1135.745408,0,11,0.430722,0.647348,0.631434,0.0,0.497453,0.012155,0.038737,0.001154,0.0,0.647348,0.0,0.012155,0.219551,1.000000e-10,0.247548,1.000000e-10,55693.214945,1.104879e+07,4.898026e-22,0.0,0.0,2.981519e-19,0.217370,0.261808,-3.158385e-09,3.158384e-12,3.158385e-06,3.158385e-06,0.000153,0.0
405070,31542,31543,31542,1,2,1298.001,0.001,162.255592,-8584.965336,1135.745408,0,11,0.427581,0.647351,0.629903,0.0,0.494948,0.012155,0.037904,0.001146,0.0,0.647351,0.0,0.012155,0.223678,1.000000e-10,0.250592,1.000000e-10,55763.401824,1.106851e+07,4.797955e-22,0.0,0.0,2.949113e-19,0.216458,0.261582,-3.102960e-09,3.102960e-12,3.102960e-06,3.102960e-06,0.000153,0.0

ids=(33914, 33915, 33914)

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
350314,33914,33915,33914,1,2,1190.001,0.001,947.648294,3.533025,242.352706,1,11,0.908700,0.916920,2.249735,0.0,0.848670,0.008989,1.023223,0.000202,0.0,0.916920,0.0,0.008989,0.042948,1.000000e-10,0.241820,1.000000e-10,7935.500017,7.388200e+02,3.929606e-24,0.0,0.0,2.189047e-20,0.850718,0.854225,-1.196987e-10,1.196986e-13,1.196987e-07,1.196987e-07,0.000792,0.0
350797,33914,33915,33914,1,2,1191.001,0.001,948.648294,-10.924551,242.352706,1,11,0.905679,0.916923,2.242247,0.0,0.846468,0.008989,1.007213,0.000202,0.0,0.916923,0.0,0.008989,0.043278,1.000000e-10,0.241806,1.000000e-10,7968.474611,3.473501e+05,3.922040e-24,0.0,0.0,2.184975e-20,0.847239,0.852029,-3.658748e-09,3.658748e-12,3.658748e-06,3.658748e-06,0.000788,0.0
351278,33914,33915,33914,1,2,1192.001,0.001,949.648294,-28.713258,242.352706,1,11,0.902035,0.916927,2.237252,0.0,0.843797,0.008989,0.988129,0.000202,0.0,0.916927,0.0,0.008989,0.043676,1.000000e-10,0.241777,1.000000e-10,7987.191572,7.583874e+05,3.900569e-24,0.0,0.0,2.180918e-20,0.844571,0.850914,-3.629755e-09,3.629755e-12,3.629755e-06,3.629755e-06,0.000787,0.0
351756,33914,33915,33914,1,2,1193.001,0.001,950.648294,-46.340559,242.352706,1,11,0.898499,0.916930,2.231963,0.0,0.841019,0.008989,0.970178,0.000202,0.0,0.916930,0.0,0.008989,0.044062,1.000000e-10,0.241687,1.000000e-10,8007.828477,1.149805e+06,3.881058e-24,0.0,0.0,2.176872e-20,0.841816,0.849663,-3.400504e-09,3.400504e-12,3.400504e-06,3.400504e-06,0.000784,0.0
352237,33914,33915,33914,1,2,1194.001,0.001,951.648294,-63.592676,242.352706,1,11,0.895110,0.916933,2.226220,0.0,0.838125,0.008989,0.953583,0.000201,0.0,0.916933,0.0,0.008989,0.044433,1.000000e-10,0.241527,1.000000e-10,8031.339833,1.518424e+06,3.864365e-24,0.0,0.0,2.172837e-20,0.838922,0.848207,-3.379183e-09,3.379183e-12,3.379183e-06,3.379183e-06,0.000782,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472643,33914,33915,33914,1,2,1414.001,0.001,137.249623,-3291.135949,1276.751377,0,11,0.644398,0.917511,1.692045,0.0,0.656861,0.008982,0.205711,0.001978,0.0,0.917511,0.0,0.008982,0.083188,1.000000e-10,0.224732,1.000000e-10,13940.220773,1.643237e+05,1.058143e-22,0.0,0.0,6.690706e-19,0.590141,0.693477,-1.530423e-11,1.530356e-14,1.530423e-08,1.530423e-08,0.000558,0.0
473272,33914,33915,33914,1,2,1415.001,0.001,138.249623,-3291.501302,1276.751377,0,11,0.644385,0.917511,1.692023,0.0,0.656852,0.008982,0.205696,0.001961,0.0,0.917511,0.0,0.008982,0.083192,1.000000e-10,0.224730,1.000000e-10,13940.533729,1.658495e+05,1.044626e-22,0.0,0.0,6.605345e-19,0.590130,0.693471,-1.530517e-11,1.530451e-14,1.530517e-08,1.530517e-08,0.000558,0.0
473900,33914,33915,33914,1,2,1416.001,0.001,139.249623,-3291.866788,1276.751377,0,11,0.644372,0.917511,1.692001,0.0,0.656842,0.008982,0.205682,0.001945,0.0,0.917511,0.0,0.008982,0.083195,1.000000e-10,0.224729,1.000000e-10,13940.841545,1.673753e+05,1.031378e-22,0.0,0.0,6.521676e-19,0.590119,0.693465,-1.530606e-11,1.530541e-14,1.530606e-08,1.530606e-08,0.000558,0.0
474531,33914,33915,33914,1,2,1417.001,0.001,140.249623,-3292.232407,1276.751377,0,11,0.644359,0.917512,1.691980,0.0,0.656833,0.008982,0.205668,0.001928,0.0,0.917512,0.0,0.008982,0.083199,1.000000e-10,0.224728,1.000000e-10,13941.144510,1.689011e+05,1.018390e-22,0.0,0.0,6.439654e-19,0.590109,0.693459,-1.530692e-11,1.530627e-14,1.530692e-08,1.530692e-08,0.000558,0.0
475164,33914,33915,33914,1,2,1418.001,0.001,141.249623,-3292.598157,1276.751377,0,11,0.644345,0.917512,1.691958,0.0,0.656824,0.008982,0.205654,0.001912,0.0,0.917512,0.0,0.008982,0.083202,1.000000e-10,0.224726,1.000000e-10,13941.442898,1.704269e+05,1.005656e-22,0.0,0.0,6.359235e-19,0.590099,0.693453,-1.530773e-11,1.530709e-14,1.530773e-08,1.530773e-08,0.000558,0.0

ids=(35164, 35165, 35164)

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
36608,35164,35165,35164,1,2,386.001,0.001,152.472299,1.612871,233.528701,0,11,0.615609,0.914531,1.783999,0.0,0.613332,0.009016,0.149295,0.001742,0.0,0.914531,0.0,0.009016,0.091635,1.000000e-10,0.213908,1.000000e-10,10288.295650,3.218430e+00,7.302564e-23,0.0,0.0,5.527831e-19,0.615869,0.737857,-2.136253e-13,2.130725e-16,2.136253e-10,2.136253e-10,0.000611,0.0
36821,35164,35165,35164,1,2,387.001,0.001,153.472299,-2.877566,233.528701,0,11,0.613669,0.914533,1.780404,0.0,0.613614,0.009016,0.147141,0.001728,0.0,0.914533,0.0,0.009016,0.092266,1.000000e-10,0.214296,1.000000e-10,10312.702083,2.225487e+05,7.201992e-23,0.0,0.0,5.464296e-19,0.614158,0.736868,-2.773293e-09,2.773292e-12,2.773293e-06,2.773293e-06,0.000609,0.0
37036,35164,35165,35164,1,2,388.001,0.001,154.472299,-9.285043,233.528701,0,11,0.610949,0.914536,1.780664,0.0,0.613038,0.009016,0.144167,0.001715,0.0,0.914536,0.0,0.009016,0.093165,1.000000e-10,0.214504,1.000000e-10,10301.266750,5.308218e+05,7.055298e-23,0.0,0.0,5.401905e-19,0.613587,0.737676,-2.725043e-09,2.725042e-12,2.725043e-06,2.725043e-06,0.000610,0.0
37256,35164,35165,35164,1,2,389.001,0.001,155.472299,-15.708773,233.528701,0,11,0.608277,0.914539,1.780842,0.0,0.612443,0.009016,0.141297,0.001702,0.0,0.914539,0.0,0.009016,0.094064,1.000000e-10,0.214702,1.000000e-10,10290.709979,8.294637e+05,6.913537e-23,0.0,0.0,5.340620e-19,0.612996,0.738441,-2.675315e-09,2.675315e-12,2.675315e-06,2.675315e-06,0.000610,0.0
37481,35164,35165,35164,1,2,390.001,0.001,156.472299,-22.141661,233.528701,0,11,0.605653,0.914541,1.780926,0.0,0.611825,0.009015,0.138529,0.001689,0.0,0.914541,0.0,0.009015,0.094964,1.000000e-10,0.214889,1.000000e-10,10281.124362,1.118643e+06,6.776635e-23,0.0,0.0,5.280417e-19,0.612383,0.739157,-2.624922e-09,2.624921e-12,2.624922e-06,2.624922e-06,0.000611,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183472,35164,35165,35164,1,2,855.001,0.001,621.472299,-7080.155486,233.528701,0,11,0.201581,0.914945,1.141256,0.0,0.294597,0.009011,0.008522,0.000332,0.0,0.914945,0.0,0.009011,0.201581,1.000000e-10,0.294597,1.000000e-10,17175.208905,1.960841e+07,1.579610e-24,0.0,0.0,4.603812e-20,0.295063,0.584777,-3.771421e-10,3.771421e-13,3.771421e-07,3.771421e-07,0.000366,0.0
183932,35164,35165,35164,1,2,856.001,0.001,622.472299,-7109.982927,233.528701,0,11,0.201205,0.914946,1.140371,0.0,0.294217,0.009011,0.008492,0.000332,0.0,0.914946,0.0,0.009011,0.201205,1.000000e-10,0.294217,1.000000e-10,17192.314885,1.961347e+07,1.571641e-24,0.0,0.0,4.590734e-20,0.294683,0.584508,-3.762093e-10,3.762093e-13,3.762093e-07,3.762093e-07,0.000365,0.0
184394,35164,35165,35164,1,2,857.001,0.001,623.472299,-7139.906690,233.528701,0,11,0.200829,0.914946,1.139487,0.0,0.293838,0.009011,0.008461,0.000331,0.0,0.914946,0.0,0.009011,0.200829,1.000000e-10,0.293838,1.000000e-10,17209.429869,1.961850e+07,1.563722e-24,0.0,0.0,4.577714e-20,0.294304,0.584240,-3.752807e-10,3.752806e-13,3.752807e-07,3.752807e-07,0.000365,0.0
184857,35164,35165,35164,1,2,858.001,0.001,624.472299,-7169.927054,233.528701,0,11,0.200455,0.914947,1.138604,0.0,0.293460,0.009011,0.008431,0.000330,0.0,0.914947,0.0,0.009011,0.200455,1.000000e-10,0.293460,1.000000e-10,17226.553875,1.962351e+07,1.555852e-24,0.0,0.0,4.564752e-20,0.293925,0.583971,-3.743586e-10,3.743585e-13,3.743586e-07,3.743586e-07,0.000365,0.0
185322,35164,35165,35164,1,2,859.001,0.001,625.472299,-7200.044303,233.528701,0,11,0.200081,0.914947,1.137723,0.0,0.293082,0.009011,0.008401,0.000330,0.0,0.914947,0.0,0.009011,0.200081,1.000000e-10,0.293082,1.000000e-10,17243.686909,1.962849e+07,1.548030e-24,0.0,0.0,4.551847e-20,0.293548,0.583703,-3.734346e-10,3.734345e-13,3.734346e-07,3.734346e-07,0.000364,0.0

ids=(35280, 35281, 35280)

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
413768,35280,35281,35280,1,2,1314.001,0.001,231.888077,4.565414,1082.112923,0,11,0.482437,0.622088,1.345670,0.0,0.479838,0.012484,0.053799,0.000723,0.0,0.622088,0.0,0.012484,0.164358,1.000000e-10,0.196935,1.000000e-10,13342.533938,229.200196,8.337062e-23,0.0,0.0,1.477100e-19,0.480584,0.539763,-2.002110e-10,2.002109e-13,2.002110e-07,2.002110e-07,0.000471,0.0
414314,35280,35281,35280,1,2,1315.001,0.001,232.888077,-31.142184,1082.112923,0,11,0.478008,0.622092,1.351038,0.0,0.481138,0.012484,0.052035,0.000719,0.0,0.622092,0.0,0.012484,0.168263,1.000000e-10,0.199698,1.000000e-10,13236.099656,373855.284080,8.064381e-23,0.0,0.0,1.465913e-19,0.481445,0.543012,-4.683175e-09,4.683175e-12,4.683175e-06,4.683175e-06,0.000475,0.0
414862,35280,35281,35280,1,2,1316.001,0.001,233.888077,-67.532187,1082.112923,0,11,0.473613,0.622096,1.356762,0.0,0.482103,0.012484,0.050350,0.000715,0.0,0.622096,0.0,0.012484,0.172273,1.000000e-10,0.202496,1.000000e-10,13126.155327,732297.904090,7.796606e-23,0.0,0.0,1.454858e-19,0.482423,0.546416,-4.440800e-09,4.440800e-12,4.440800e-06,4.440800e-06,0.000479,0.0

In [13]:
df.loc[df.idbin==33914].sort_values('tphys')

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
349831,33914,33915,33914,1,2,1189.385221,0.001,947.032515,3.563248,242.352706,1,11,0.908706,0.916920,2.261284,0.0,0.848661,0.008989,1.023204,0.000203,0.0,0.916920,0.0,0.008989,0.042947,1.000000e-10,0.241816,1.000000e-10,7874.800774,1.913123e+00,3.895007e-24,0.0,0.0,2.191566e-20,0.855086,0.858609,-1.001100e-15,9.791841e-19,1.001100e-12,1.001100e-12,0.000798,0.0
350314,33914,33915,33914,1,2,1190.001000,0.001,947.648294,3.533025,242.352706,1,11,0.908700,0.916920,2.249735,0.0,0.848670,0.008989,1.023223,0.000202,0.0,0.916920,0.0,0.008989,0.042948,1.000000e-10,0.241820,1.000000e-10,7935.500017,7.388200e+02,3.929606e-24,0.0,0.0,2.189047e-20,0.850718,0.854225,-1.196987e-10,1.196986e-13,1.196987e-07,1.196987e-07,0.000792,0.0
350797,33914,33915,33914,1,2,1191.001000,0.001,948.648294,-10.924551,242.352706,1,11,0.905679,0.916923,2.242247,0.0,0.846468,0.008989,1.007213,0.000202,0.0,0.916923,0.0,0.008989,0.043278,1.000000e-10,0.241806,1.000000e-10,7968.474611,3.473501e+05,3.922040e-24,0.0,0.0,2.184975e-20,0.847239,0.852029,-3.658748e-09,3.658748e-12,3.658748e-06,3.658748e-06,0.000788,0.0
351278,33914,33915,33914,1,2,1192.001000,0.001,949.648294,-28.713258,242.352706,1,11,0.902035,0.916927,2.237252,0.0,0.843797,0.008989,0.988129,0.000202,0.0,0.916927,0.0,0.008989,0.043676,1.000000e-10,0.241777,1.000000e-10,7987.191572,7.583874e+05,3.900569e-24,0.0,0.0,2.180918e-20,0.844571,0.850914,-3.629755e-09,3.629755e-12,3.629755e-06,3.629755e-06,0.000787,0.0
351756,33914,33915,33914,1,2,1193.001000,0.001,950.648294,-46.340559,242.352706,1,11,0.898499,0.916930,2.231963,0.0,0.841019,0.008989,0.970178,0.000202,0.0,0.916930,0.0,0.008989,0.044062,1.000000e-10,0.241687,1.000000e-10,8007.828477,1.149805e+06,3.881058e-24,0.0,0.0,2.176872e-20,0.841816,0.849663,-3.400504e-09,3.400504e-12,3.400504e-06,3.400504e-06,0.000784,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472643,33914,33915,33914,1,2,1414.001000,0.001,137.249623,-3291.135949,1276.751377,0,11,0.644398,0.917511,1.692045,0.0,0.656861,0.008982,0.205711,0.001978,0.0,0.917511,0.0,0.008982,0.083188,1.000000e-10,0.224732,1.000000e-10,13940.220773,1.643237e+05,1.058143e-22,0.0,0.0,6.690706e-19,0.590141,0.693477,-1.530423e-11,1.530356e-14,1.530423e-08,1.530423e-08,0.000558,0.0
473272,33914,33915,33914,1,2,1415.001000,0.001,138.249623,-3291.501302,1276.751377,0,11,0.644385,0.917511,1.692023,0.0,0.656852,0.008982,0.205696,0.001961,0.0,0.917511,0.0,0.008982,0.083192,1.000000e-10,0.224730,1.000000e-10,13940.533729,1.658495e+05,1.044626e-22,0.0,0.0,6.605345e-19,0.590130,0.693471,-1.530517e-11,1.530451e-14,1.530517e-08,1.530517e-08,0.000558,0.0
473900,33914,33915,33914,1,2,1416.001000,0.001,139.249623,-3291.866788,1276.751377,0,11,0.644372,0.917511,1.692001,0.0,0.656842,0.008982,0.205682,0.001945,0.0,0.917511,0.0,0.008982,0.083195,1.000000e-10,0.224729,1.000000e-10,13940.841545,1.673753e+05,1.031378e-22,0.0,0.0,6.521676e-19,0.590119,0.693465,-1.530606e-11,1.530541e-14,1.530606e-08,1.530606e-08,0.000558,0.0
474531,33914,33915,33914,1,2,1417.001000,0.001,140.249623,-3292.232407,1276.751377,0,11,0.644359,0.917512,1.691980,0.0,0.656833,0.008982,0.205668,0.001928,0.0,0.917512,0.0,0.008982,0.083199,1.000000e-10,0.224728,1.000000e-10,13941.144510,1.689011e+05,1.018390e-22,0.0,0.0,6.439654e-19,0.590109,0.693459,-1.530692e-11,1.530627e-14,1.530692e-08,1.530692e-08,0.000558,0.0
475164,33914,33915,33914,1,2,1418.001000,0.001,141.249623,-3292.598157,1276.751377,0,11,0.644345,0.917512,1.691958,0.0,0.656824,0.008982,0.205654,0.001912,0.0,0.917512,0.0,0.008982,0.083202,1.000000e-10,0.224726,1.000000e-10,13941.442898,1.704269e+05,1.005656e-22,0.0,0.0,6.359235e-19,0.590099,0.693453,-1.530773e-11,1.530709e-14,1.530773e-08,1.530773e-08,0.000558,0.0

In [10]:
mask = df.mass_1.diff().abs()<0.01
df[mask | (mask.shift(-1))]

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
34,78054,78055,78054,1,2,48.178133,-0.009734,4.129655,31.232939,44.048478,4,12,13.942397,1.094668,201.275304,0.0,119.999873,0.006973,77118.253313,0.143384,4.712918,1.094668,0.667000,0.006973,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,19.362225,1.627105e+06,9.639936e-22,6.829780e-10,1.785579e-07,4.139444e-16,120.147203,38.770079,-1.785579e-07,6.829776e-10,0.0,0.0,0.233428,0.0
35,78028,78029,78028,1,2,48.624460,0.015612,2.570187,31.573522,46.054273,4,11,13.935152,1.199640,356.493115,0.0,210.328784,0.005682,79518.694173,0.270390,4.879845,1.199640,0.659355,0.005682,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,8.091281,5.567458e+06,4.442510e-22,1.219318e-09,2.812629e-07,1.080434e-15,210.287306,70.555466,-2.812629e-07,1.219317e-09,0.0,0.0,0.548450,0.0
61,77942,77943,77942,1,2,61.137072,-0.000284,3.022134,39.812567,58.114938,4,11,11.947165,1.158637,414.621672,0.0,240.739003,0.006202,55397.894615,0.217147,4.143931,1.158637,0.581447,0.006202,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,4.322320,3.831058e+06,2.221135e-22,1.118007e-09,2.086454e-07,7.780535e-16,240.724615,84.970453,-2.086454e-07,1.118006e-09,0.0,0.0,0.739255,0.0
62,77920,77921,77920,1,2,61.841895,-0.016134,1.260679,40.072117,60.581216,4,11,11.943322,1.241546,549.035050,0.0,315.477893,0.005118,54790.231729,0.619998,4.164022,1.241546,0.556431,0.005118,6.036883e-02,1.000000e-10,9.346959e+01,1.000000e-10,2.619104,7.069323e+06,3.598873e-22,1.794278e-09,2.838250e-07,3.731280e-15,315.746032,114.811574,-2.838250e-07,1.794274e-09,0.0,0.0,1.123080,0.0
67,77914,77915,77914,1,2,66.744374,0.000061,4.729780,44.570985,62.014594,2,11,11.038808,0.952061,199.742021,0.0,116.841617,0.008596,33264.999838,0.106633,2.509523,0.952061,0.390032,0.008596,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,12.627921,2.372266e+04,7.886348e-22,3.208640e-10,7.020153e-08,2.648250e-16,117.794820,39.553489,-7.020153e-08,3.208637e-10,0.0,0.0,0.258421,0.0
68,77926,77927,77926,1,2,67.632199,-0.014460,6.389349,43.498501,61.242849,4,11,11.036290,1.072927,329.258585,0.0,190.694129,0.007226,45862.255883,0.084807,3.799126,1.072927,0.542593,0.007226,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,4.603718,1.267881e+06,1.149552e-22,8.402354e-10,1.525277e-07,1.882295e-16,191.100242,67.524789,-1.525277e-07,8.402352e-10,0.0,0.0,0.544247,0.0

In [11]:
df.sort_values(['idbin', 'tphys'])

,idbin,id1,id2,j1,j2,tphys,dtm,age,epoch_1,epoch_2,kstar_1,kstar_2,mass_1,mass_2,sep,ecc,rad_1,rad_2,lumin_1,lumin_2,massc_1,massc_2,radc_1,radc_2,menv_1,menv_2,renv_1,renv_2,ospin_1,ospin_2,dmt_1,dmt_2,dmr_1,dmr_2,rol_1,rol_2,dmdt_1,dmdt_2,dm1,dm2,tb,Lx
128,16784,16785,16784,1,2,140.954402,-0.000018,0.593611,95.256481,140.360791,2,11,7.171267,0.832288,204.806859,0.0,115.916779,0.009942,6120.300934,0.920484,1.401639,0.832288,0.262063,0.009942,2.756704e+00,1.000000e-10,7.432669e+01,1.000000e-10,10.874455,4.744094e+03,1.313534e-20,1.490407e-10,1.973253e-08,6.719157e-15,115.972884,44.214239,-1.973253e-08,1.490340e-10,0.000021,0.000004,0.328415,2.419824e+40
130,16784,16785,16784,1,2,142.562705,0.009703,2.201914,140.954043,140.360791,7,11,1.401359,0.832315,0.661117,0.0,0.278001,0.009941,845.358461,0.223502,0.000000,0.832315,0.000000,0.009941,1.401359e+00,1.000000e-10,2.780006e-01,1.000000e-10,41870.190638,6.578608e+03,4.960823e-18,1.975692e-11,1.867520e-10,8.096256e-16,0.280772,0.221361,-1.867520e-10,1.975611e-11,0.000000,0.000000,0.000114,0.000000e+00
118,41342,41343,41342,1,2,130.255523,-0.000104,0.313460,88.786278,129.942063,3,11,7.568853,0.870670,230.899006,0.0,130.330132,0.009508,7439.227280,1.773054,1.507614,0.870670,0.275889,0.009508,3.224590e+00,1.000000e-10,8.744863e+01,1.000000e-10,9.004201,6.509746e+03,2.693023e-20,1.938248e-10,2.556338e-08,1.795864e-14,130.913308,49.719761,-2.556338e-08,1.938069e-10,0.000000,0.000000,0.382845,0.000000e+00
119,41342,41343,41342,1,2,133.580136,0.008289,3.638073,130.253180,129.942063,7,11,1.506684,0.870750,0.745367,0.0,0.315294,0.009507,1267.617778,0.131956,0.000000,0.870750,0.000000,0.009507,1.506684e+00,1.000000e-10,3.152939e-01,1.000000e-10,37464.725967,1.279737e+04,1.754852e-18,3.492116e-11,3.428318e-10,3.659850e-16,0.318361,0.247895,-3.428318e-10,3.492079e-11,0.000000,0.000000,0.000132,0.000000e+00
120,41342,41343,41342,1,2,133.606136,0.001000,3.664073,130.204728,129.942063,7,11,1.496668,0.880758,0.737182,0.0,0.314182,0.009394,1243.923767,0.132385,0.000000,0.880758,0.000000,0.009394,1.496668e+00,1.000000e-10,3.141819e-01,1.000000e-10,36896.958711,1.118745e+06,1.735721e-18,3.529214e-11,3.424001e-10,3.614489e-16,0.313680,0.246270,-8.117037e-06,8.116730e-06,0.008117,0.008117,0.000130,5.648531e-260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9,107092,107093,107092,1,2,40.120295,-0.010592,2.479724,25.785703,37.640571,4,12,15.829049,1.287775,319.705270,0.0,189.842329,0.004441,106060.879654,0.302304,5.601063,1.287775,0.725563,0.004441,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,11.097089,9.288762e+06,4.424707e-22,1.622073e-09,3.948264e-07,1.266256e-15,189.975477,62.231273,-3.948264e-07,1.622071e-09,0.000000,0.000000,0.437987,0.000000e+00
25,107094,107095,107094,1,2,44.329545,-0.008935,6.810454,27.465181,37.519091,4,12,14.059548,1.422886,461.472878,0.0,266.100905,0.001452,82196.780117,0.104427,4.992515,1.422886,0.655415,0.001452,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,2.663237,5.905352e+07,2.984073e-24,2.184005e-09,3.658506e-07,2.570653e-16,266.371815,95.752811,-3.658506e-07,2.184005e-09,0.000000,0.000000,0.798634,0.000000e+00
6,107098,107099,107098,1,2,38.340213,0.013085,0.975232,24.032817,37.364980,4,12,16.426867,1.258077,282.781391,0.0,168.715420,0.004883,105649.605521,0.829458,5.571124,1.258077,0.727548,0.004883,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,17.924551,8.165350e+06,3.583094e-21,1.213162e-09,3.449513e-07,5.870967e-15,169.333164,54.071612,-3.449513e-07,1.213156e-09,0.000000,0.000000,0.358445,0.000000e+00
8,107108,107109,107108,1,2,39.171763,0.013213,4.473010,24.720337,34.698753,4,12,15.724681,1.344403,298.930634,0.0,176.224783,0.003481,104086.504287,0.160602,5.535872,1.344403,0.723332,0.003481,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,9.330700,1.045449e+07,1.094537e-22,1.492187e-09,3.480111e-07,4.919882e-16,176.491341,59.043420,-3.480111e-07,1.492186e-09,0.000000,0.000000,0.396551,0.000000e+00
2,107116,107117,107116,1,2,36.490429,-0.005365,4.230232,22.949755,32.260197,4,12,16.513056,1.383664,253.401391,0.0,149.854188,0.002653,115217.067124,0.176282,5.796403,1.383664,0.749770,0.002653,1.000000e-10,1.000000e-10,1.000000e-10,1.000000e-10,14.109628,1.629952e+07,1.056480e-22,1.518530e-09,3.574014e-07,5.645065e-16,150.003169,49.755410,-3.574014e-07,1.518530e-09,0.000000,0.000000,0.302256,0.000000e+00

## Time steps consistency

In [ ]:
df.idbin.unique()

Problem with 78724, 78712
- everytime we pass through the standev step (1 Myr), e.g. tphys==5.0, there is a mishap in dtm and tphys.diff
- evolv2b.f l:1019 is probably responsible 
- use loc for better visibility!

Problem with 78660
- negative dtm

Problem with 107114, 78204
- seems to be different systems

In [ ]:
idbins = [78724, 78712]
idbins = [107114, 78204]
for idbin in idbins:  # df.idbin.unique():
    print(f"{idbin=}")
    dfi = df.query(f'idbin=={idbin}').copy()#.loc[lambda x: x.tphys.between(4.95, 5.05)]#.reset_index()

    dfi['dtphys']=dfi.tphys.diff()
    display(dfi[['tphys','dtm','dtphys','kstar_1','kstar_2','sep']])

    display(dfi[['tphys','dtm','dtphys','kstar_1','kstar_2','sep']].query('abs(dtm-dtphys)>0.00001'))

## Mass transfer rates

In [ ]:
df['Mdot'] = df['dm1']/df['tb']

In [ ]:
display(df.Mdot.describe())
# df[df.idbin!=77748].Mdot.apply(np.log10).hist(nbins=40, log_y=True)
df.Mdot.apply(np.log10).hist(nbins=40, log_y=True)

- negative values (probably because RLOF was calculated for non-RLfilling systems
- peak at 4e-8 (for older systems)

In [ ]:
df[df.Mdot.apply(np.log10).between(-7.5, -7)].idbin.value_counts()

In [ ]:
df.query('idbin==77748')

## X-ray luminosity

In [ ]:
display(df.Lx.describe())
df.Lx.apply(np.log10).hist(nbins=40, log_y=True)

In [ ]:
df.plot(kind='scatter', x='dtm', y='Lx', log_y=True)

- negative values
- good range of values
- reversed(?) relation for Lx(dtm)

In [ ]:
df['mass_don'] = df.mass_2.where(df.j1==2, df.mass_1)
df['rad_don'] = df.rad_2.where(df.j1==2, df.rad_1)
df['rol_don'] = df.rol_2.where(df.j1==2, df.rol_1)
df['kstar_don'] = df.kstar_2.where(df.j1==2, df.kstar_1)

df['mass_acc'] = df.mass_2.where(df.j1==1, df.mass_1)
df['rad_acc'] = df.rad_2.where(df.j1==1, df.rad_1)
df['rol_acc'] = df.rol_2.where(df.j1==1, df.rol_1)
df['kstar_acc'] = df.kstar_2.where(df.j1==1, df.kstar_1)

In [ ]:
df.query('Lx>0').plot(kind='scatter', x='tphys', y='Lx', log_y=True, size='dtm', color='kstar_acc', opacity=0.5).update_traces(marker_line_width=0)

### Dynamical simulations

In [ ]:
dfd = pd.read_csv('xrb_dyn.dat', names=names, sep='\s+')
dfd

In [ ]:
dfd.tphys.describe()

In [ ]:
for idbin in [78666]:  # dfd.idbin.unique():
    print(f"{idbin=}")
    dfi = dfd.query(f'idbin=={idbin}').copy()#.loc[lambda x: x.tphys.between(4.95, 5.05)]#.reset_index()

    dfi['dtphys']=dfi.tphys.diff()
    display(dfi[['tphys','dtm','dtphys','kstar_1','kstar_2','sep']])

    display(dfi[['tphys','dtm','dtphys','kstar_1','kstar_2','sep']].query('abs(dtm-dtphys)>0.00001'))

In [ ]:
a=None
f"{a}"

In [ ]:
mdon = 16.642224
Rdon = 4.493982
Rldon = 4.538849
3e-6 * min(mdon, 5)**2 * np.log(Rdon/Rldon)**3

In [ ]:
(df.rad_don / df.rol_don).describe()

In [ ]:
df.Lx.describe()

In [ ]:
df['Lx'] = df.apply(lambda row: Lxacc(row.mass_acc, row.rad_acc, row.dm1, row.kstar_acc), axis=1)

In [ ]:
with pd.option_context('display.max_columns', None):
    display(dff)

In [ ]:
dff['Lx'] = dff.apply(lambda row: 1.2e35 * row[f'mass({int(row.j2)})'] * row[f'mdot'] * 1e6 / row[f'rad({int(row.j2)})'], axis=1)

In [ ]:
dff.Lx.describe()

In [ ]:
df[(df.idbin != df.id1)]

In [ ]:
(df.tphys - df.age - df['epoch(2)']).agg(['min','max'])

In [ ]:
df.j2.unique()

In [ ]:
df[['dmdt(1)', 'dmdt(2)']].describe()

In [ ]:
# Mass tranfser rate for donors (j1==2)
df.query('j1==2')['dmdt(2)'].describe()#.apply(np.log10).hist()

In [ ]:
df.query('j1==1')['dmdt(1)'].describe()

In [ ]:
df[(df['j1'] == 1) & (df['dmdt(1)'] < 0)]

In [ ]:
df[(df['j1'] == 2) & (df['dmdt(2)'] < 0)]

In [ ]:
df[(df['dmdt(1)']<0) & (df['dmdt(2)'] < 0)]

In [ ]:
id1 = 78736
df.query('id1==@id1 or id2==@id1')

In [ ]:
snapshot = ml.read_snapshot('snapshot.dat')
snapshot

In [ ]:
snapshot.query("idd1==@id1 or idd2==@id1")

In [ ]:
from pathlib import Path

In [ ]:
datapath = Path('./zzz')
if not datapath.exists():
    print("FILE DO NOT EXIST!!!")

In [ ]:
import re

In [ ]:
re.findall("\line.replace(' ','')

In [ ]:
def row_to_dict(line):
    row = {}
    for k, v in map(lambda x: x.split('='), re.findall(rf'\w+=[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eEdD][+-]?\d+)?', line.replace(' ',''))):
        if v.isnumeric():
            row[k]=int(v)
        else:
            try: 
                row[k]=float(v)
            except:  # is actually string (object)
                row[k]=v

    return row

def read_zzz(path, row_selector=None, row_transformer=None, return_dataframe=True):
    data = []
    with open(datapath, 'r') as f:
        while line := f.readline():
            if row_selector is not None and not row_selector(line):
                continue
            if row_transformer is not None:
                line = row_to_dict(line)
            data.append(line)
    if return_dataframe:
        return pd.DataFrame(data)
    else:
        return data
    
read_zzz(datapath, row_selector = lambda line: line.startswith(' LH3:'), row_transformer=row_to_dict)

In [ ]:
import seaborn as sns
sns.lineplot(data=df, x='tphys', y='B')

In [ ]:
1.9

In [ ]:
df = read_zzz(datapath,
              row_selector = lambda line: line.startswith(' LH1:'), 
              row_transformer=row_to_dict
             )
df

In [ ]:
df.tphys-df.epoch-df.tacc

In [ ]:
(df.k==13).sum()

In [ ]:
import seaborn as sns
sns.lineplot(data=df, x='tphys', y='B')

In [ ]:
df.groupby(['id','k']).plot(x='tphys',y='B')